function build_figure(data)                          
%%                                             获取屏幕参数
screen=get(0,'screensize');
w=screen(3);

h=screen(4);
data.axes_w=data.axes_h*h/w;
data.cut_w=data.cut_h*h/w;
%%                                             建立程序主界面
hfigure=figure('color',[0.6,0.6,0.6],'Position',...         
    [0,0.05*h,w,0.91*h],'name','五子棋',...
    'numbertitle','off','menubar','none');
haxes=axes('parent',hfigure,'position',[data.cut_w,data.cut_h,data.axes_w,data.axes_h]);
%%                                             建立棋盘坐标系
data.haxes=haxes;
data.hfigure=hfigure;
%%                                             设立棋盘参数
hold on;                                                    
axis([0,data.len,0,data.len]);
set(haxes,'XTick',0:data.len,'YTick',0:data.len);
axis manual
grid on
box off
set(haxes,'XTickLabel','','YTickLabel','');
%%                                             绘制UI
uicontrol(hfigure,'style','Text','Units','normalized',...
    'Position',[0.7,0.8,0.2,0.1],'string','五 子 棋',...
    'Back',[0.6,0.6,0.6],'FontSize',25,'fontweight','bold');
uicontrol(hfigure,'style','Text','Units','normalized',...
    'Position',[0.7,0.55,0.2,0.05],'string','点击按钮在多个选项之间切换',...
    'Back',[0.6,0.6,0.6],'FontSize',10);
uicontrol(hfigure,'style','Text','Units','normalized',...
    'Position',[0.65,0.7,0.1,0.05],'string','模式选择',...
    'Back',[0.6,0.6,0.6],'FontSize',11);
data.hmode=uicontrol(hfigure,'Style', 'pushbutton', 'Units','normalized','String', '玩家对玩家',...
    'Position', [0.65,0.65,0.1,0.05],...
    'Callback', 'mode_callback(data)','FontSize',11);                                  %模式按钮
data.horder=uicontrol(hfigure,'Style', 'pushbutton', 'Units','normalized','String', '不需规定先后手',...
    'Position', [0.8,0.65,0.12,0.05],...
    'Callback', 'order_callback(data)','enable','off','FontSize',11);                                 %先后手按钮
uicontrol(hfigure,'style','Text','Units','normalized',...
    'Position',[0.8,0.7,0.1,0.05],'string','规则选择',...
    'Back',[0.6,0.6,0.6],'FontSize',11);                                           
data.hstart=uicontrol(hfigure,'Style', 'pushbutton', 'Units','normalized','String', '开始',...
    'Position', [0.75,0.35,0.1,0.07],...
    'Callback', 'start_callback(data)','fontsize',12);                                 %开始按钮
data.hinfo=uicontrol(hfigure,'style','Text','Units','normalized',...
    'Position',[0.75,0.1,0.11,0.05],'string','欢迎',...                    %信息显示
    'Back',[0.6,0.6,0.6],'fontAngle','normal','fontsize',15,'fontweight','bold');
end